version: '3'

tasks:
  poetry-init:
    cmds:
      - poetry add pip
      - poetry add requests
  get-pyzed:
    deps:
      - poetry-init
    cmds:
      - poetry run python get_python_api.py
  build-environment:
    deps:
      - get-pyzed
    cmds:
      - poetry install
      - poetry run python -m pip install numpy==1.26.4 --force

  run-example:
    cmds:
      - poetry run python simple/simple_example.py